project_admin_teste:
    resource: "@ProjectAdminBundle/Resources/config/routing/teste.yml"
    prefix:   /teste

project_admin_homepage:
    path:     /hello/{name}
    defaults: { _controller: ProjectAdminBundle:Default:index }
