services:
    app.teste_configure_menu_listener: { class: '%app.teste_configure_menu_listener.class%', tags: [{ name: kernel.event_listener, event: app.menu_configure, method: onMenuConfigure }] }
parameters:
    app.teste_configure_menu_listener.class: Project\AdminBundle\EventListener\TesteMenuListener
