_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

core_alerta:
    resource: "@CoreAlertaBundle/Resources/config/routing.yml"
    prefix:   /admin/alerta

core_configs:
    resource: "@CoreConfigsBundle/Resources/config/routing.yml"
    prefix:   /admin/configs


core_upload:
    resource: "@CoreUploadBundle/Resources/config/routing.yml"
    prefix:   /admin/uploads

core_admin_user:
    resource: "@CoreUserBundle/Resources/config/routing.yml"
    prefix:   /admin/users
    
core_admin:
    resource: "@CoreAdminBundle/Resources/config/routing.yml"
    prefix:   /admin
    
logout:
    path: /logout
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /admin/groups
    
admin_user_group_permissions:
    path:  /admin/groups/{groupName}/permissions
    defaults: { _controller: "CoreUserBundle:GroupPermissions:index" }


admin_home:
    path: /admin/
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: admin_dashboard
        permanent: true


sg_datatables_bundle:
    resource: "@SgDatatablesBundle/Controller/"
    type:     annotation
