core_admin:
    resource: "@CoreAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

core_upload:
    resource: "@CoreUploadBundle/Resources/config/routing.yml"
    prefix:   /

project_external:
    resource: "@ProjectExternalBundle/Resources/config/routing.yml"
    prefix:   /
    


project_admin:
    resource: "@ProjectAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

core_user:
    resource: "@CoreUserBundle/Resources/config/routing.yml"
    prefix:   /admin/users

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

logout:
    path: /logout
    
fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /admin/groups
    
admin_user_group_permissions:
    pattern:  /admin/groups/{groupName}/permissions
    defaults: { _controller: "CoreUserBundle:GroupPermissions:index" }
    
admin:
    resource: "@JordiLlonchCrudGeneratorBundle/Resources/config/routing.yml"
    prefix: /admin
    
# HOME
admin_home:
    path: /admin
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: admin_dashboard
        permanent: true
        
external_home:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: project_external_homepage
        permanent: true