services:
    app.user_configure_menu_listener: { class: '%app.user_configure_menu_listener.class%', tags: [{ name: kernel.event_listener, event: app.menu_configure, method: onMenuConfigure }] }
    core_user.registration.form.type:
        class: Core\UserBundle\Form\Type\RegistrationFormType
        tags:
            - { name: form.type, alias: core_user_registration }
parameters:
    app.user_configure_menu_listener.class: Core\UserBundle\EventListener\UserMenuListener
