services:
    app.user_configure_menu_listener:  
        class: '%app.user_configure_menu_listener.class%'
        arguments: ["@security.token_storage", "@security.authorization_checker"]
        tags: 
            - { name: kernel.event_listener, event: app.menu_configure, method: onMenuConfigure }
    app.user_configure_permissions_listener:  
        class: '%app.user_configure_permissions_listener.class%'
        tags: 
            - { name: kernel.event_listener, event: Core_user.permissions.tree, method: addModulePermissions } 
    Core_user.registration.form.type:
        class: Core\Bundle\UserBundle\Form\Type\RegistrationFormType
        tags:
            - { name: form.type, alias: Core_user_registration }
    Core_user.profile.form.type:
        class: Core\Bundle\UserBundle\Form\Type\ProfileFormType
        tags:
            - { name: form.type, alias: Core_user_profile }
    Core_user.group.form.type:
        class: Core\Bundle\UserBundle\Form\Type\GroupFormType
        arguments: [%fos_user.model.group.class%]
        tags:
            - { name: form.type, alias: Core_user_group }
    security.system_roles:
        class: %security.system_roles.class%
        arguments: ["@event_dispatcher"]
            
    app.profile_update:  
        class: Core\Bundle\UserBundle\EventListener\ProfileUpdate
        arguments: ["@fos_user.user_manager.default", "@router"]
        tags: 
            - { name: kernel.event_listener, event: fos_user.resetting.reset.success, method: redirecionarInstancia } 
parameters:
    app.user_configure_menu_listener.class: Core\Bundle\UserBundle\EventListener\UserMenuListener
    app.user_configure_permissions_listener.class: Core\Bundle\UserBundle\EventListener\UserPermissionsListener
    security.system_roles.class: Core\Bundle\UserBundle\Services\SystemRoles
