parameters:
    app.admin_configure_menu_listener.class: JordiLlonch\Bundle\CrudGeneratorBundle\EventListener\ConfigureMenuListener

services:
    app.admin_configure_menu_listener:
        class: %app.admin_configure_menu_listener.class%
        tags:
          - { name: kernel.event_listener, event: app.menu_configure, method: onMenuConfigure }