parameters:
    glifery.entity_hidden_type.entity_form_type.class: Glifery\EntityHiddenTypeBundle\Form\Type\EntityHiddenType

services:
    glifery.entity_hidden_type.entity_form_type:
        class: %glifery.entity_hidden_type.entity_form_type.class%
        arguments: ["@doctrine"]
        tags:
        - { name: form.type, alias: entity_hidden }